language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test # C++14
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-5 # C++14

script: 
  - qmake
  - make
  - ./travis_qmake_gcc_cpp14_qt